name: DoNotDisturb
version: ${project.version}
description: "Stop people from annoying you."
main: org.simondoesstuff.plugindonotdisturb.PluginDoNotDisturb
api-version: 1.16
depend: [ProtocolLib]
author: simondoesstuff
commands:
  dnd:
    description: "The root command for all DND commands."
    usage: "/dnd help"
    aliases:
      - donotdisturb